
# First try with layer 21

interp-cli train-distance-probe data/activations/gpt-oss-20b/size9_numenvs1000_trajectorysteps20/observability_full_full_prompt/raw_acts_last_prompt --layer 21 --verbose 1  --eval-split 0.2 --reg-coeff 0.1 --learning-rate 0.0003 --num-epochs 300 --batch-size 16384 --use-mlp --mlp-hidden-size 1024
