#!/usr/bin/env python3
"""
Script to balance activation files by sampling equal numbers of each cell type.
This works on the .pt files generated by the activation gathering process.
"""

import argparse
import os
import random
from pathlib import Path

import torch
import numpy as np


def balance_activation_files(
    activations_dir: str,
    output_dir: str,
    target_samples_per_class: int = 1000,
    seed: int = 42
) -> None:
    """
    Balance activation files by sampling equal numbers of each cell type.
    
    Args:
        activations_dir: Directory containing acts_*.pt files
        output_dir: Directory to save balanced activation files
        target_samples_per_class: Target number of samples per class
        seed: Random seed for reproducibility
    """
    random.seed(seed)
    np.random.seed(seed)
    
    activations_dir = Path(activations_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Find all activation files
    activation_files = {}
    for file_path in activations_dir.glob("acts_*.pt"):
        class_name = file_path.stem.replace("acts_", "")
        activation_files[class_name] = file_path
    
    if not activation_files:
        raise ValueError(f"No activation files found in {activations_dir}")
    
    print(f"🔍 Found activation files for classes: {list(activation_files.keys())}")
    
    # Load and analyze current class distribution
    print("\n📊 Current class distribution:")
    class_data = {}
    for class_name, file_path in activation_files.items():
        activations = torch.load(file_path)
        class_data[class_name] = activations
        print(f"  {class_name}: {len(activations):,} samples")
    
    # Balance each class
    balanced_data = {}
    
    for class_name, activations in class_data.items():
        available_samples = len(activations)
        
        print(f"\n🎯 Processing {class_name} class:")
        print(f"  Available samples: {available_samples:,}")
        print(f"  Target samples: {target_samples_per_class:,}")
        
        if available_samples >= target_samples_per_class:
            # Sample without replacement
            indices = torch.randperm(available_samples, generator=torch.Generator().manual_seed(seed))[:target_samples_per_class]
            balanced_activations = activations[indices]
            print(f"  ✅ Sampled {target_samples_per_class:,} samples")
        else:
            # Sample with replacement to reach target
            indices = torch.randint(0, available_samples, (target_samples_per_class,), generator=torch.Generator().manual_seed(seed))
            balanced_activations = activations[indices]
            print(f"  ⚠️  Sampled {target_samples_per_class:,} samples (with replacement)")
        
        balanced_data[class_name] = balanced_activations
    
    # Save balanced activation files
    print(f"\n💾 Saving balanced activation files to {output_dir}")
    for class_name, activations in balanced_data.items():
        output_path = output_dir / f"acts_{class_name}.pt"
        torch.save(activations, output_path)
        print(f"  ✅ Saved {len(activations):,} {class_name} activations to {output_path}")
    
    print(f"\n📊 Final balanced class distribution:")
    for class_name, activations in balanced_data.items():
        print(f"  {class_name}: {len(activations):,} samples")
    
    total_samples = sum(len(activations) for activations in balanced_data.values())
    print(f"\n📈 Total samples: {total_samples:,}")


def balance_activation_files_with_oversampling(
    activations_dir: str,
    output_dir: str,
    minority_multiplier: int = 5,
    seed: int = 42
) -> None:
    """
    Balance activation files by oversampling minority classes.
    
    Args:
        activations_dir: Directory containing acts_*.pt files
        output_dir: Directory to save balanced activation files
        minority_multiplier: How many times to oversample minority classes
        seed: Random seed for reproducibility
    """
    random.seed(seed)
    np.random.seed(seed)
    
    activations_dir = Path(activations_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Find all activation files
    activation_files = {}
    for file_path in activations_dir.glob("acts_*.pt"):
        class_name = file_path.stem.replace("acts_", "")
        activation_files[class_name] = file_path
    
    if not activation_files:
        raise ValueError(f"No activation files found in {activations_dir}")
    
    print(f"🔍 Found activation files for classes: {list(activation_files.keys())}")
    
    # Load and analyze current class distribution
    print("\n📊 Current class distribution:")
    class_data = {}
    for class_name, file_path in activation_files.items():
        activations = torch.load(file_path)
        class_data[class_name] = activations
        print(f"  {class_name}: {len(activations):,} samples")
    
    # Find the majority class size
    majority_size = max(len(activations) for activations in class_data.values())
    print(f"\n🎯 Majority class size: {majority_size:,}")
    
    # Balance each class
    balanced_data = {}
    
    for class_name, activations in class_data.items():
        current_size = len(activations)
        
        print(f"\n🔄 Processing {class_name} class:")
        print(f"  Current size: {current_size:,}")
        
        if class_name in ['agent', 'goal']:
            # Oversample minority classes
            target_size = min(current_size * minority_multiplier, majority_size)
            if target_size > current_size:
                # Sample with replacement
                additional_indices = torch.randint(
                    0, current_size, 
                    (target_size - current_size,), 
                    generator=torch.Generator().manual_seed(seed)
                )
                additional_activations = activations[additional_indices]
                balanced_activations = torch.cat([activations, additional_activations], dim=0)
                print(f"  ✅ Oversampled to {target_size:,} samples")
            else:
                balanced_activations = activations
                print(f"  ✅ Kept original {current_size:,} samples")
        else:
            # For wall and empty, sample down to a reasonable size
            if current_size > majority_size:
                indices = torch.randperm(current_size, generator=torch.Generator().manual_seed(seed))[:majority_size]
                balanced_activations = activations[indices]
                print(f"  ✅ Downsampled to {majority_size:,} samples")
            else:
                balanced_activations = activations
                print(f"  ✅ Kept original {current_size:,} samples")
        
        balanced_data[class_name] = balanced_activations
    
    # Save balanced activation files
    print(f"\n💾 Saving balanced activation files to {output_dir}")
    for class_name, activations in balanced_data.items():
        output_path = output_dir / f"acts_{class_name}.pt"
        torch.save(activations, output_path)
        print(f"  ✅ Saved {len(activations):,} {class_name} activations to {output_path}")
    
    print(f"\n📊 Final balanced class distribution:")
    for class_name, activations in balanced_data.items():
        print(f"  {class_name}: {len(activations):,} samples")
    
    total_samples = sum(len(activations) for activations in balanced_data.values())
    print(f"\n📈 Total samples: {total_samples:,}")


def main():
    parser = argparse.ArgumentParser(description="Balance activation files for probing")
    parser.add_argument("activations_dir", help="Directory containing acts_*.pt files")
    parser.add_argument("output_dir", help="Directory to save balanced activation files")
    parser.add_argument(
        "--method", 
        choices=["equal", "oversample"], 
        default="equal",
        help="Balancing method: 'equal' for equal samples per class, 'oversample' for oversampling minority classes"
    )
    parser.add_argument(
        "--target-samples", 
        type=int, 
        default=1000,
        help="Target number of samples per class (for equal method)"
    )
    parser.add_argument(
        "--minority-multiplier", 
        type=int, 
        default=5,
        help="Multiplier for oversampling minority classes (for oversample method)"
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    
    args = parser.parse_args()
    
    if args.method == "equal":
        balance_activation_files(
            args.activations_dir, 
            args.output_dir, 
            args.target_samples, 
            args.seed
        )
    elif args.method == "oversample":
        balance_activation_files_with_oversampling(
            args.activations_dir, 
            args.output_dir, 
            args.minority_multiplier, 
            args.seed
        )


if __name__ == "__main__":
    main()
